<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>TC_amazon_validate_search_item_With_ExcelSheet_001</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>3</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>374be2dd-40db-48ac-8a9f-14bd5cc7d925</testSuiteGuid>
   <testCaseLink>
      <guid>95774ce5-1611-4b9e-a1f1-5654d22dba02</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Data_driven_testing/TC_amazon_validate_search_item_With_ExcelSheet_001</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>9c520d04-502a-4b15-82b1-ea8dbb21ec99</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/Amazon_testdata/TC_Amazon_category_Excelsheet-001</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>9c520d04-502a-4b15-82b1-ea8dbb21ec99</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>category</value>
         <variableId>9368b123-bbc0-4b2d-9ac3-0f78ae160708</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>9c520d04-502a-4b15-82b1-ea8dbb21ec99</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Item</value>
         <variableId>a738e231-05fa-49e4-afd5-29132ea9a0c7</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
