<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_United States</name>
   <tag></tag>
   <elementGuidId>839bca05-bee6-46b4-987a-00fa0e91a023</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#icp-touch-link-country</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='icp-touch-link-country']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>fa47e175-d077-4d5a-996e-d114a8b9614f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/customer-preferences/country?ie=UTF8&amp;preferencesReturnUrl=%2F&amp;ref_=footer_icp_cp</value>
      <webElementGuid>f5789e8e-8f6b-4728-a029-498bb35c1be9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Choose a country/region for shopping.</value>
      <webElementGuid>bc5406cb-354d-41b6-8806-4a76bac471c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>icp-button</value>
      <webElementGuid>c98e832e-3233-4c6e-93a7-d8be0f1644bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>icp-touch-link-country</value>
      <webElementGuid>a37b37aa-67b6-4974-9252-f9619a54d220</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
  United States
</value>
      <webElementGuid>c867d65a-b2f2-4e32-88ba-e608721ea132</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;icp-touch-link-country&quot;)</value>
      <webElementGuid>f342eded-ebbc-47ac-b688-a5bd5c24661a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='icp-touch-link-country']</value>
      <webElementGuid>50cfaf88-3a46-4de4-a918-3620008c839e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='navFooter']/div[3]/span[2]/div/a[3]</value>
      <webElementGuid>50ebea63-05ec-471b-b68e-1f303af50c14</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/customer-preferences/country?ie=UTF8&amp;preferencesReturnUrl=%2F&amp;ref_=footer_icp_cp')]</value>
      <webElementGuid>af0356ff-2c0e-490e-9064-a4d1b838cc31</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[2]/div/a[3]</value>
      <webElementGuid>8326d4f6-7f5e-4541-aaf8-759044c37b8a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/customer-preferences/country?ie=UTF8&amp;preferencesReturnUrl=%2F&amp;ref_=footer_icp_cp' and @id = 'icp-touch-link-country' and (text() = '
  United States
' or . = '
  United States
')]</value>
      <webElementGuid>fdc6d994-0fe8-449d-80fd-4cb7a560f07f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
