<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>TC_amazon_validate_search_item-001</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>3</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>5f0f0a36-da80-4608-97a8-41c5c081154b</testSuiteGuid>
   <testCaseLink>
      <guid>6f92d1f6-95d1-4206-a90b-1ece3786dfb1</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Data_driven_testing/TC_amazon_validate_search_item-001</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>34469ada-3c35-4d02-9e89-98cca5098ad1</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/Amazon_testdata/TC_Amazon_category_Excelsheet-001</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>34469ada-3c35-4d02-9e89-98cca5098ad1</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>category</value>
         <variableId>9368b123-bbc0-4b2d-9ac3-0f78ae160708</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>34469ada-3c35-4d02-9e89-98cca5098ad1</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Item</value>
         <variableId>a738e231-05fa-49e4-afd5-29132ea9a0c7</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
